# Generated by Django 3.1.7 on 2022-03-04 12:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('hacker_news_item', models.BooleanField()),
                ('creator', models.CharField(max_length=1000)),
                ('hn_id', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hn_id', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
                ('hn_parent', models.CharField(max_length=200)),
                ('kids', models.CharField(max_length=400)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.story')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
