# Generated by Django 3.2.12 on 2022-03-05 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hacker_news_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 13, 38, 19, 383745)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
