# Generated by Django 3.2.12 on 2022-03-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='Welcome', max_length=1000),
            preserve_default=False,
        ),
    ]
