# Generated by Django 3.2.12 on 2022-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
