# Generated by Django 3.2.12 on 2022-03-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220315_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='parent_comment',
        ),
    ]
